const path = require("path");

const exec = require("child_process").execSync;
const fs = require("fs");

export default async function handle(req, res) {
  const here = exec("ls ./").toString().split("\n");
  const parent = exec("ls ../").toString().split("\n");
  const grandParent = exec("ls ../../").toString().split("\n");
  const grandGrandParent = exec("ls ../../../").toString().split("\n");
  const parentDb = exec("ls -a /var/task/").toString().split("\n");
  const parentDbS = exec("ls -a /var").toString().split("\n");
  const parentDbSs = exec("ls -a /var/task/.next/server/pages/api")
    .toString()
    .split("\n");
  const parentDbSpages = exec("ls -a /var/task/.next/server/pages")
    .toString()
    .split("\n");

  const b = {
    f: {
      dir: "/var/task/.next/server/pages/api",
      here: [
        "___next_launcher.js",
        "node_modules",
        "package.json",
        "___vc_bridge.js",
        "",
      ],
      parent: [
        "adm",
        "cache",
        "db",
        "empty",
        "games",
        "gopher",
        "kerberos",
        "lang",
        "lib",
        "local",
        "lock",
        "log",
        "mail",
        "nis",
        "opt",
        "preserve",
        "rapid",
        "run",
        "runtime",
        "spool",
        "task",
        "telemetry",
        "tmp",
        "tracer",
        "yp",
        "",
      ],
      grandParent: [
        "bin",
        "boot",
        "dev",
        "etc",
        "home",
        "lib",
        "lib64",
        "media",
        "mnt",
        "opt",
        "proc",
        "root",
        "run",
        "sbin",
        "srv",
        "sys",
        "tmp",
        "usr",
        "var",
        "",
      ],
      grandGrandParent: [
        "bin",
        "boot",
        "dev",
        "etc",
        "home",
        "lib",
        "lib64",
        "media",
        "mnt",
        "opt",
        "proc",
        "root",
        "run",
        "sbin",
        "srv",
        "sys",
        "tmp",
        "usr",
        "var",
        "",
      ],
      parentDb: [
        ".",
        "..",
        ".env",
        ".next",
        "___next_launcher.js",
        "node_modules",
        "package.json",
        "___vc_bridge.js",
        "",
      ],
      parentDbS: [
        ".",
        "..",
        "adm",
        "cache",
        "db",
        "empty",
        "games",
        "gopher",
        "kerberos",
        "lang",
        "lib",
        "local",
        "lock",
        "log",
        "mail",
        "nis",
        "opt",
        "preserve",
        "rapid",
        "run",
        "runtime",
        "spool",
        "task",
        "telemetry",
        "tmp",
        "tracer",
        "yp",
        "",
      ],
      parentDbSs: [
        ".",
        "..",
        "a.js",
        "feed.js",
        "find.js",
        "ls.js",
        "path.js",
        "",
      ],
      parentDbSpages: [
        ".",
        "..",
        "404.html",
        "api",
        "_app.js",
        "_document.js",
        "_error.js",
        "",
      ],
    },
  };

  res.json({
    dir: __dirname,
    here,
    parent,
    grandParent,
    grandGrandParent,
    parentDb,
    parentDbS,
    parentDbSs,
    parentDbSpages,
  });
}
